/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description liveness：只證明「這個 process 還活著、能回應 HTTP」。
         *
         *     決定 3：刻意不碰資料庫。Docker healthcheck 打的是這一個端點——
         *     如果這裡查資料庫，資料庫短暫抖動就會讓容器被判定不健康而重啟，
         *     但重啟並不能解決資料庫的問題，只會在資料庫恢復期間把 API 也弄掉。
         *     要看資料庫通不通，打 /api/health/ready。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description readiness：資料庫連不上時回 503（不是 500），給人／腳本判斷
         *     「現在能不能服務」用。決定 3：這個端點不接到 Docker 的自動重啟上。
         *
         *     try 只包住真的會拋例外的那一行（SELECT 1）：資料庫連線失敗或查詢失敗
         *     都是從 db.execute 拋出來的，包更大範圍只會讓「這個 500 到底是資料庫
         *     的問題還是別的東西壞了」變得看不出來。
         */
        get: operations["health_ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description 登出這一台裝置：這張 refresh token 所屬的整條鏈立刻失效，不能再換發新票。
         *
         *     對無效、過期、已經登出過的 token 一律回 204——這個端點本來就是冪等的。
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout All
         * @description 登出所有裝置：這個帳號名下每一條 refresh token 鏈立刻失效，不能再換發新票。
         *
         *     **請注意：已經發出去的 access token 不受影響，最多還能繼續用到它自己的
         *     到期時間（目前 15 分鐘）。** 這個端點擋得住的是「換新票」，擋不住
         *     「手上這張還沒過期的票」——如果懷疑帳號被盜用，這 15 分鐘的空窗期
         *     是目前系統的已知限制，不是這個端點沒做好。
         */
        post: operations["logout_all_api_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description 超出規格第 7.1 節的新增（計畫 3 Task 3）：時區設定進去卻改不掉是 bug。
         *
         *     範圍嚴格限制在 display_name / timezone。沒有路徑參數 —— 這個端點改的
         *     永遠是 token 解出來的那個使用者，`user` 本身就是 `get_current_user`
         *     已經驗證過的那一列，這裡不再另外做一次「擁有權」查詢。
         *
         *     用 exclude_unset 而不是 exclude_none：兩個欄位在資料庫都是 NOT NULL，
         *     這個區別今天不可見，但這是為了以後加可為 null 的欄位時養成的習慣。
         */
        patch: operations["update_me_api_me_patch"];
        trace?: never;
    };
    "/api/foods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Foods */
        get: operations["search_foods_api_foods_get"];
        put?: never;
        /** Create Food */
        post: operations["create_food_api_foods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/frequent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Frequent Foods
         * @description 使用者最常吃的食物，依吃過的次數多到少排序（規格第 11 節：每天走最多次的路徑）。
         */
        get: operations["list_frequent_foods_api_foods_frequent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recent Foods
         * @description 使用者最近吃過的食物，依最後一次吃的時間新到舊排序。
         */
        get: operations["list_recent_foods_api_foods_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/{food_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Food */
        get: operations["read_food_api_foods__food_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/{food_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Revisions */
        get: operations["list_revisions_api_foods__food_id__revisions_get"];
        put?: never;
        /** Propose Revision */
        post: operations["propose_revision_api_foods__food_id__revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/{food_id}/portions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Portions */
        get: operations["list_portions_api_foods__food_id__portions_get"];
        put?: never;
        /** Create Portion */
        post: operations["create_portion_api_foods__food_id__portions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/food-revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pending Revisions */
        get: operations["list_pending_revisions_api_admin_food_revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/food-revisions/{revision_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Revision */
        post: operations["approve_revision_api_admin_food_revisions__revision_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/food-revisions/{revision_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Revision */
        post: operations["reject_revision_api_admin_food_revisions__revision_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Meals
         * @description 依「使用者當地的一天」列出當天吃的餐（計畫 3 決定 1）。
         *
         *     `day_bounds()` 把使用者的時區換算成 UTC 的半開區間 `[start, end)`——
         *     用 `<`，不是 `<=`：`<=` 會讓恰好落在當地午夜的一餐同時屬於兩天。
         *     省略 `date` 時預設「使用者時區的今天」，靠 `today_in_timezone()` 算，
         *     不是伺服器所在時區的今天，也不是 UTC 的今天。
         *
         *     兩次查詢，跟這一天有幾筆餐、每筆餐有幾個項目都無關：
         *     第一次查出這天的所有 Meal，第二次用 `meal_id IN (...)` 一次把所有
         *     Meal 的項目、revision、food 都 join 回來，在記憶體裡依 meal_id 分組——
         *     不是對每筆 Meal 各查一次項目（那會是「這天吃了幾餐」次的往返）。
         */
        get: operations["list_meals_api_meals_get"];
        put?: never;
        /** Create Meal */
        post: operations["create_meal_api_meals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meals/{meal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Meal
         * @description 讀單一餐點：只有 2 次查詢，跟項目數無關（見 `_item_join_query`）。
         */
        get: operations["read_meal_api_meals__meal_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Meal
         * @description 刪一餐。`meal_items` 靠 `ON DELETE CASCADE` 跟著走，這裡不逐筆刪。
         *
         *     擁有權檢查（`_load_owned_meal`）必須在刪除**之前**：先查到、確認是
         *     自己的，才刪；不能「先刪、再檢查」，那種順序下「回 404」跟「真的沒刪掉」
         *     會脫鉤 —— 對一個一查就砍的實作，只斷言狀態碼的測試看不出差別。
         *
         *     照片檔案的清理跟 `DELETE .../photo` 同一個順序原則（計畫 3 Task 16、
         *     規格第 8 節）：先讓 DB 正確（`db.delete` + `commit`），檔案清理放在
         *     commit 之後、盡力刪除（`delete_photo` 本身是 best-effort，失敗只記警告，
         *     不影響這個請求已經成功的事實）。`photo_path` 要在 commit **之前**存進
         *     區域變數 —— 物件被刪除後再讀它的屬性不保證還拿得到值。
         */
        delete: operations["delete_meal_api_meals__meal_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Meal
         * @description 只改餐點本身：`eaten_at` / `meal_type` / `note`（計畫 3 決定 2）。
         *     項目不在這個端點的範圍內 —— 那是 `POST/DELETE .../items` 的事。
         *
         *     用 `exclude_unset` 決定要更新哪些欄位（沒帶的欄位維持原樣），
         *     `MealUpdateRequest` 自己的驗證器已經擋掉 `eaten_at` / `meal_type`
         *     的顯式 `null`，所以流到這裡的 `None` 只可能是合法的 `note` 清空。
         */
        patch: operations["update_meal_api_meals__meal_id__patch"];
        trace?: never;
    };
    "/api/meals/{meal_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Meal Item
         * @description 加一個項目到一餐（計畫 3 決定 2：項目的增刪走這裡，不是 PATCH）。
         *
         *     食物與份量的解析完全重用 `_resolve_item`（Task 7 抽出來的那個函式，
         *     現在底下呼叫的 `load_visible_portion` 也已經提升到 `app/food_visibility.py`
         *     —— 這是它的第二個呼叫者）。不重新驗證一次可見性邏輯：複製一份的話，
         *     日後修一個安全性 bug 只會修到一邊，這是計畫在 Task 7 實測發現裡明講的。
         *
         *     餐點的擁有權查詢在「解析項目」之前 —— 加到別人的餐要 404，不能先驗證
         *     完項目才發現餐不是自己的。
         */
        post: operations["add_meal_item_api_meals__meal_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meals/{meal_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Meal Item
         * @description 刪一個項目。
         *
         *     擁有權沿著 `meal_items.meal_id -> meals.user_id` 檢查（先用
         *     `_load_owned_meal` 確認 `meal_id` 是自己的一餐，再確認這個 `item_id`
         *     真的屬於**這一筆** `meal_id`）—— 不能只檢查 `item_id` 存在，那會讓
         *     任何登入的使用者都能刪掉別人的項目，只要猜得到 id。
         */
        delete: operations["delete_meal_item_api_meals__meal_id__items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meals/{meal_id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Meal Photo
         * @description 讀一餐的照片（計畫 3 Task 15）。
         *
         *     規格第 8 節：照片**不**透過靜態檔案服務提供 —— 每一次讀取都要先經過這個
         *     端點驗證 JWT 與擁有權，不是靠 UUID 檔名猜不到。掛 `StaticFiles` 在
         *     `photo_dir` 上會讓這道檢查形同虛設，一旦網址外流就永久有效；擁有權檢查
         *     沿用 `_load_owned_meal`，跟其他所有餐點端點是同一個函式、同一條規則。
         *
         *     DB 有 `photo_path` 但檔案不在磁碟上是正常操作下可達的狀態（`delete_photo()`
         *     是 best-effort 設計），一律用實際讀檔的結果判斷 —— 讀不到就是 404，
         *     不能讓 `FileNotFoundError` 逃逸成未處理的 500。
         */
        get: operations["read_meal_photo_api_meals__meal_id__photo_get"];
        put?: never;
        /**
         * Upload Meal Photo
         * @description 上傳一餐的照片；已經有照片的話取代舊的。
         *
         *     取代舊照片的順序不能換（計畫 3 Task 14，規格第 8 節：兩種孤兒檔案的
         *     嚴重性不對稱 —— 多一個沒人引用的檔案只是浪費磁碟，少一個被引用的
         *     檔案是壞掉的功能，所以要讓 DB 先正確，檔案容許暫時落後）：
         *
         *     1. 先把新檔案寫到磁碟（`save_photo`）—— 這一步失敗完全不影響 DB 或舊檔
         *     2. 再把新的 `photo_path` 寫進 DB 並 commit —— DB 正確是第一優先
         *     3. 最後才盡力刪掉舊檔案（`delete_photo` 是 best-effort，失敗只記警告）
         *
         *     如果顛倒 2、3 的順序：先刪舊檔、DB 寫入才發現失敗，使用者原本的照片
         *     已經沒了，新照片卻沒有被登記 —— 兩份都不見。
         *
         *     擁有權檢查在讀取、解碼上傳內容之前：上傳到別人的餐直接 404，
         *     不必先花力氣處理圖片內容。
         */
        post: operations["upload_meal_photo_api_meals__meal_id__photo_post"];
        /**
         * Delete Meal Photo
         * @description 刪掉一餐的照片（計畫 3 Task 16）。
         *
         *     一律「先 DB、後檔案」（規格第 8 節：兩種孤兒檔案的嚴重性不對稱 ——
         *     多一個沒人引用的檔案只是浪費磁碟，少一個被引用的檔案是壞掉的功能，
         *     所以要讓 DB 先正確）：
         *
         *     1. 先把 `photo_path` 清成 NULL 並 commit —— DB 正確是第一優先
         *     2. 再盡力刪掉磁碟上的檔案（`delete_photo` 是 best-effort，失敗只記警告，
         *        不讓這個請求因此失敗）
         *
         *     如果顛倒順序：先刪檔案、DB 寫入才發現失敗，`photo_path` 還指著一個
         *     已經不存在的檔案 —— 跟 Task 15 要防的「DB 有 photo_path 但檔案不見」
         *     是同一種壞狀態，只是這次是自己造成的。
         *
         *     `old_path` 要在 commit **之前**存進區域變數：`meal.photo_path` 已經被
         *     設成 None，commit 之後再讀就拿不到原本的路徑了。
         */
        delete: operations["delete_meal_photo_api_meals__meal_id__photo_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supplements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Supplements */
        get: operations["search_supplements_api_supplements_get"];
        put?: never;
        /** Create Supplement */
        post: operations["create_supplement_api_supplements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supplements/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Today
         * @description 今日待打卡清單：把「計畫」與「實際」對起來（陷阱 2）。
         *
         *     `supplement_plans.effective_from/to` 是 `date`，`supplement_intakes.taken_at`
         *     是 `timestamptz`，兩種型別的「今天」判斷方式不同，但**只算一次**
         *     `today_in_timezone()`，同時餵給計畫的日期比較與 `day_bounds()` 的
         *     timestamptz 半開區間 —— 不能分開各自算一次，否則使用者當地時區跟 UTC
         *     交界的那幾小時，兩者會對到不同的日子（清單顯示昨天的計畫、今天的打卡）。
         *
         *     `day_bounds()` 回傳半開區間 `[start, end)`，用 `<`，不是 `<=`：
         *     `<=` 會讓恰好落在當地午夜的一筆打卡同時屬於兩天，4b 的依從率會把
         *     那次攝取算兩次（計畫 3 Task 9 同一個坑）。
         */
        get: operations["list_today_api_supplements_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supplement-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_api_supplement_plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_supplement_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supplement-plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Plan
         * @description 刪一筆計畫。擁有權檢查必須在刪除之前（`_load_owned_plan`）——
         *     不能「先刪、再檢查」，那種順序下「回 404」跟「真的沒刪掉」會脫鉤
         *     （計畫 3 Task 11 實測過這個坑），對一個一查就砍的實作，只斷言狀態碼
         *     的測試看不出差別。
         *
         *     `supplement_intakes.plan_id` 是 `ON DELETE SET NULL`（model 裡宣告）：
         *     打卡紀錄是歷史，不因為計畫被刪而消失，只是不再屬於任何計畫 —— 這件事
         *     完全由資料庫的外鍵處理，這裡不需要、也不應該手動去更新 intakes。
         */
        delete: operations["delete_plan_api_supplement_plans__plan_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Plan
         * @description 修改一筆計畫 —— 陷阱 3：這不是原地修改，是「關閉舊期間、開新期間」。
         *
         *     舊列的 dose / time_of_day 完全不動，只有 effective_to 被設成生效日；
         *     新列從生效日起、承接沒有明確送的欄位（沿用舊列的值）。這正是有效期間制
         *     的意義：歷史不動，4b 的依從率才能靠舊列本身回答「當時該吃幾次」。
         *
         *     **順序不能換**（陷阱 3 已實測）：EXCLUDE 約束逐列立即檢查，UPDATE 一定
         *     要先 flush，INSERT 的檢查才看得到已經關閉的舊期間；反過來的話新舊兩列
         *     會重疊，直接違反約束。這裡刻意分兩次 flush（而不是一次 flush 讓
         *     SQLAlchemy 自己決定 unit-of-work 內的順序），把順序寫死、不依賴實作細節。
         */
        patch: operations["update_plan_api_supplement_plans__plan_id__patch"];
        trace?: never;
    };
    "/api/supplement-intakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Intake */
        post: operations["create_intake_api_supplement_intakes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supplement-intakes/{intake_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Intake
         * @description 刪一筆打卡紀錄。擁有權檢查必須在刪除之前（`_load_owned_intake`）——
         *     順序反了的話「回 404」跟「真的沒刪掉」會脫鉤（計畫 3 Task 11、
         *     本計畫 Task 7 都實測過這個坑），對一個一查就砍的實作，只斷言狀態碼
         *     的測試看不出差別。
         */
        delete: operations["delete_intake_api_supplement_intakes__intake_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Or Get Target
         * @description 規格第 7.6 節的兩行合在同一個路由裡，用 `date` 有沒有帶區分：
         *
         *     - 沒帶 `date`：`GET /api/targets` 列出我所有的期間（陣列，含已關閉的）。
         *     - 帶了 `date`：`GET /api/targets?date=` 回那一天生效的那一筆，
         *       沒有則回 `null`——**200，不是 404**。「沒設目標」是正常狀態，不是
         *       「目標不存在所以出錯」；4b 的統計端點要能分辨「沒設目標」跟
         *       「這筆目標 id 不存在」，是完全不同的兩件事。
         *
         *     「那一天生效」用半開區間判斷（`effective_from <= date < effective_to`，
         *     `effective_to IS NULL` 視為無窮遠的未來）——跟資料庫 EXCLUDE 約束用的
         *     `daterange(..., '[)')` 是同一個邊界規則，兩處不能有一處用 `<=`。
         */
        get: operations["list_or_get_target_api_targets_get"];
        put?: never;
        /** Create Target */
        post: operations["create_target_api_targets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/targets/{target_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Target
         * @description 修改一筆目標 —— 決定 1：不是原地修改，是「關閉舊期間、開新期間」。
         *
         *     舊列的四個營養素、label 完全不動，只有 effective_to 被設成新期間的
         *     起始日。這正是有效期間制的意義：三月的目標值必須維持「三月當時設的值」，
         *     `/stats/range`（Task 8）才能用「當天生效的目標」算歷史達成率，不能用
         *     改完之後的最新值重算過去。
         *
         *     **順序不能換**（陷阱 3 已在 supplement_plans 實測、這裡同構）：
         *     EXCLUDE 約束逐列立即檢查，UPDATE 舊列一定要先 flush，INSERT 新列的
         *     檢查才看得到已經關閉的舊期間；反過來的話新舊兩列會重疊，直接違反約束。
         */
        patch: operations["update_target_api_targets__target_id__patch"];
        trace?: never;
    };
    "/api/stats/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Daily Stats
         * @description 回一天的實際攝取、目標、比例與食物/補劑分項（決定 2：只回數字，
         *     不判斷達標與否——同一個 110% 在減脂期跟增肌期意義相反，那個判斷留給
         *     前端）。
         *
         *     省略 `date` 時預設「使用者時區的今天」，跟 `GET /api/meals?date=`、
         *     `GET /api/supplements/today` 用同一個 `today_in_timezone()`（陷阱 1：
         *     三個端點對「同一天」的判斷必須完全一致）。
         *
         *     固定 3 次查詢（食物一次、補劑一次、目標一次），跟這一天有幾個餐點項目、
         *     幾筆補劑打卡都無關——`app/stats.py` 的 `daily_macros()` 已經保證了
         *     食物與補劑各自只發一次查詢，這裡再加一次目標查詢。
         */
        get: operations["get_daily_stats_api_stats_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Range Stats
         * @description 一段期間的每日趨勢與補劑依從率（決定 2：只回數字，不判斷達標與否）。
         *
         *     `from` / `to` **兩端都含** —— 使用者說「9/1 到 9/7」預期的是 7 天。
         *     內部一律換成半開區間 `[from, to+1)` 再交給 `app/stats.py`，
         *     跟 `day_bounds()` 的慣例一致，不讓兩種區間慣例在同一個檔案裡並存。
         *
         *     固定 5 次查詢（食物、補劑、目標、計畫、打卡各一次），跟期間有幾天無關。
         */
        get: operations["get_range_stats_api_stats_range_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BaseUnit
         * @enum {string}
         */
        BaseUnit: "g" | "ml";
        /** Body_upload_meal_photo_api_meals__meal_id__photo_post */
        Body_upload_meal_photo_api_meals__meal_id__photo_post: {
            /** File */
            file: string;
        };
        /** BreakdownResponse */
        BreakdownResponse: {
            food: components["schemas"]["MacrosResponse"];
            supplement: components["schemas"]["MacrosResponse"];
        };
        /**
         * DailyStatsResponse
         * @description `GET /api/stats/daily` 的回應（Task 7，決定 2）。
         *
         *     `target` 與 `ratio` 整組是 `NullableMacrosResponse | None`——最外層的
         *     `None` 代表「這一天完全沒有生效的目標」（決定 2：不是 0，也不是省略），
         *     跟裡面個別欄位的 `None`（陷阱 3：目標存在，但這個營養素沒設）是
         *     兩層不同的「沒有」，不能混為一談。
         */
        DailyStatsResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            actual: components["schemas"]["MacrosResponse"];
            target: components["schemas"]["NullableMacrosResponse"] | null;
            ratio: components["schemas"]["NullableMacrosResponse"] | null;
            breakdown: components["schemas"]["BreakdownResponse"];
        };
        /**
         * DayTrendResponse
         * @description `GET /api/stats/range` 趨勢陣列裡的一天（Task 8）。
         *
         *     欄位與 `DailyStatsResponse` 的前四項刻意完全一致，包括 `target` / `ratio`
         *     的兩層 null 語意 —— 趨勢裡的一天跟單獨查那一天，意義必須一樣，
         *     否則同一個日期從兩個端點拿到不同答案。
         *
         *     沒有資料的日子 `actual` 是 0，不是把那一天從陣列裡拿掉：畫圖要連續。
         */
        DayTrendResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            actual: components["schemas"]["MacrosResponse"];
            target: components["schemas"]["NullableMacrosResponse"] | null;
            ratio: components["schemas"]["NullableMacrosResponse"] | null;
        };
        /** FoodCreateRequest */
        FoodCreateRequest: {
            /** Name */
            name: string;
            /** Brand */
            brand?: string | null;
            nutrition: components["schemas"]["NutritionInput"];
        };
        /** FoodResponse */
        FoodResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Brand */
            brand: string | null;
            /** Is Global */
            is_global: boolean;
            nutrition: components["schemas"]["NutritionResponse"] | null;
        };
        /**
         * FoodScope
         * @enum {string}
         */
        FoodScope: "all" | "global" | "mine";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LogoutRequest
         * @description 跟 RefreshRequest 形狀相同，但刻意是獨立的型別 ——
         *
         *     兩個端點的請求體日後可能各自長出欄位（例如登出帶上裝置識別），
         *     共用一個型別會讓那時候的改動被迫同時影響兩邊。
         */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * MacrosResponse
         * @description 一定有值的四個巨量營養素——沒有資料時是 0.00，不是 null（決定 2：
         *     統計只回數字）。`actual`、`breakdown.food`、`breakdown.supplement` 都用
         *     這個型別。
         */
        MacrosResponse: {
            /** Kcal */
            kcal: string;
            /** Protein G */
            protein_g: string;
            /** Fat G */
            fat_g: string;
            /** Carb G */
            carb_g: string;
        };
        /** MealCreateRequest */
        MealCreateRequest: {
            /**
             * Eaten At
             * Format: date-time
             */
            eaten_at: string;
            meal_type: components["schemas"]["MealType"];
            /** Note */
            note?: string | null;
            /** Items */
            items?: components["schemas"]["MealItemCreateRequest"][];
        };
        /** MealItemCreateRequest */
        MealItemCreateRequest: {
            /** Food Id */
            food_id: number;
            /** Quantity */
            quantity: number | string;
            /** Portion Id */
            portion_id?: number | null;
        };
        /** MealItemResponse */
        MealItemResponse: {
            /** Id */
            id: number;
            /** Food Id */
            food_id: number;
            /** Food Name */
            food_name: string;
            /** Portion Id */
            portion_id: number | null;
            /** Quantity */
            quantity: string;
            /** Quantity G */
            quantity_g: string;
            /** Kcal */
            kcal: string;
            /** Protein G */
            protein_g: string;
            /** Fat G */
            fat_g: string;
            /** Carb G */
            carb_g: string;
        };
        /** MealResponse */
        MealResponse: {
            /** Id */
            id: number;
            /**
             * Eaten At
             * Format: date-time
             */
            eaten_at: string;
            meal_type: components["schemas"]["MealType"];
            /** Note */
            note: string | null;
            /** Photo Path */
            photo_path: string | null;
            /** Items */
            items: components["schemas"]["MealItemResponse"][];
            /** Kcal */
            kcal: string;
            /** Protein G */
            protein_g: string;
            /** Fat G */
            fat_g: string;
            /** Carb G */
            carb_g: string;
        };
        /**
         * MealType
         * @enum {string}
         */
        MealType: "breakfast" | "lunch" | "dinner" | "snack";
        /**
         * MealUpdateRequest
         * @description `PATCH /api/meals/{id}` 的請求（計畫 3 決定 2）：只改餐點本身，
         *     項目的增刪走另外兩個端點（Task 12），這裡不收 `items`。
         *
         *     跟 `UpdateMeRequest` 同一種哨兵寫法：三個欄位都是 `X | None = None`，
         *     `None` 代表「這次請求沒帶這個欄位」，路由層用
         *     `model_dump(exclude_unset=True)` 決定要更新哪些。
         *
         *     但跟 `UpdateMeRequest` 不同的是，這裡三個欄位對 NOT NULL 的態度不一樣：
         *     `eaten_at` 與 `meal_type` 是 NOT NULL，顯式 `null` 必須擋在這裡 ——
         *     否則會一路流到 `setattr`，撞上 `asyncpg.NotNullViolationError` 變成
         *     已認證使用者就能觸發的 500（`UpdateMeRequest` 踩過的同一個坑）。
         *     `note` 是 nullable，`{"note": null}` 是合法輸入、必須放行到底。
         */
        MealUpdateRequest: {
            /** Eaten At */
            eaten_at?: string | null;
            meal_type?: components["schemas"]["MealType"] | null;
            /** Note */
            note?: string | null;
        };
        /**
         * NullableMacrosResponse
         * @description 四個欄位各自可能是 null（陷阱 3：目標的四個營養素欄位都可以獨立
         *     不設）。`target` 用這個型別放目標本身的值；`ratio` 用這個型別放
         *     逐欄位算出來的比例，同一個欄位在 target 是 null 時 ratio 也是 null，
         *     target 是 0 時 ratio 也是 null（除以 0 沒有意義，不能讓它變成 500）。
         */
        NullableMacrosResponse: {
            /** Kcal */
            kcal: string | null;
            /** Protein G */
            protein_g: string | null;
            /** Fat G */
            fat_g: string | null;
            /** Carb G */
            carb_g: string | null;
        };
        /** NutritionInput */
        NutritionInput: {
            /** @default g */
            base_unit: components["schemas"]["BaseUnit"];
            /** Kcal */
            kcal: number | string;
            /** Protein G */
            protein_g: number | string;
            /** Fat G */
            fat_g: number | string;
            /** Carb G */
            carb_g: number | string;
        };
        /** NutritionResponse */
        NutritionResponse: {
            base_unit: components["schemas"]["BaseUnit"];
            /** Kcal */
            kcal: string;
            /** Protein G */
            protein_g: string;
            /** Fat G */
            fat_g: string;
            /** Carb G */
            carb_g: string;
        };
        /** PendingRevisionResponse */
        PendingRevisionResponse: {
            /** Id */
            id: number;
            /** Food Id */
            food_id: number;
            /** Food Name */
            food_name: string;
            /** Food Brand */
            food_brand: string | null;
            base_unit: components["schemas"]["BaseUnit"];
            /** Kcal */
            kcal: string;
            /** Protein G */
            protein_g: string;
            /** Fat G */
            fat_g: string;
            /** Carb G */
            carb_g: string;
            status: components["schemas"]["RevisionStatus"];
            /** Change Note */
            change_note: string | null;
            /** Created By */
            created_by: number;
            /** Created By Name */
            created_by_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Kcal */
            current_kcal: string | null;
            /** Current Protein G */
            current_protein_g: string | null;
            /** Current Fat G */
            current_fat_g: string | null;
            /** Current Carb G */
            current_carb_g: string | null;
        };
        /** PortionCreateRequest */
        PortionCreateRequest: {
            /** Label */
            label: string;
            /** Grams */
            grams: number | string;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /**
             * Is Global
             * @default false
             */
            is_global: boolean;
        };
        /** PortionResponse */
        PortionResponse: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Grams */
            grams: string;
            /** Is Default */
            is_default: boolean;
            /** Is Global */
            is_global: boolean;
        };
        /**
         * RangeStatsResponse
         * @description `GET /api/stats/range?from=&to=` 的回應（Task 8）。
         *
         *     查詢參數是 `from` / `to`（規格第 7.6 節），但回應欄位叫
         *     `date_from` / `date_to` —— `from` 是 Python 保留字，當欄位名要額外的
         *     alias 機制才寫得出來，而回應欄位名不影響使用者輸入的介面。
         *
         *     區間**兩端都含**：使用者說「9/1 到 9/7」預期的是 7 天。
         *     （內部分桶仍然用半開區間，見 `app/stats.py`。）
         *
         *     `adherence` 是決定 3 定義的補劑依從率：
         *     「有打卡的 (計畫, 日) 配對數 / 應該有的配對數」，每對最多算一次。
         *     完全沒有計畫時是 `null` —— 不是 0（那會讀成「一次都沒吃」），
         *     也不是 1（那會讀成「全部做到」）。
         */
        RangeStatsResponse: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Trend */
            trend: components["schemas"]["DayTrendResponse"][];
            /** Adherence */
            adherence: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
            /**
             * Timezone
             * @default Asia/Taipei
             */
            timezone: string;
        };
        /** RevisionCreateRequest */
        RevisionCreateRequest: {
            nutrition: components["schemas"]["NutritionInput"];
            /** Change Note */
            change_note?: string | null;
        };
        /** RevisionRejectRequest */
        RevisionRejectRequest: {
            /** Reason */
            reason: string;
        };
        /** RevisionResponse */
        RevisionResponse: {
            /** Id */
            id: number;
            base_unit: components["schemas"]["BaseUnit"];
            /** Kcal */
            kcal: string;
            /** Protein G */
            protein_g: string;
            /** Fat G */
            fat_g: string;
            /** Carb G */
            carb_g: string;
            status: components["schemas"]["RevisionStatus"];
            /** Change Note */
            change_note: string | null;
            /** Created By */
            created_by: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Reviewed By */
            reviewed_by: number | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Reject Reason */
            reject_reason: string | null;
            /**
             * Is Current
             * @default false
             */
            is_current: boolean;
        };
        /**
         * RevisionStatus
         * @enum {string}
         */
        RevisionStatus: "pending" | "approved" | "rejected";
        /** SupplementCreateRequest */
        SupplementCreateRequest: {
            /** Name */
            name: string;
            /** Brand */
            brand?: string | null;
            /** Serving Unit */
            serving_unit: string;
            /** Serving Size */
            serving_size: number | string;
            /**
             * Kcal
             * @default 0
             */
            kcal: number | string;
            /**
             * Protein G
             * @default 0
             */
            protein_g: number | string;
            /**
             * Fat G
             * @default 0
             */
            fat_g: number | string;
            /**
             * Carb G
             * @default 0
             */
            carb_g: number | string;
        };
        /** SupplementIntakeCreateRequest */
        SupplementIntakeCreateRequest: {
            /** Supplement Id */
            supplement_id: number;
            /** Plan Id */
            plan_id?: number | null;
            /** Dose */
            dose: number | string;
            /**
             * Taken At
             * Format: date-time
             */
            taken_at: string;
        };
        /** SupplementIntakeResponse */
        SupplementIntakeResponse: {
            /** Id */
            id: number;
            /** Supplement Id */
            supplement_id: number;
            /** Plan Id */
            plan_id: number | null;
            /** Dose */
            dose: string;
            /**
             * Taken At
             * Format: date-time
             */
            taken_at: string;
            /** Kcal */
            kcal: string;
            /** Protein G */
            protein_g: string;
            /** Fat G */
            fat_g: string;
            /** Carb G */
            carb_g: string;
        };
        /** SupplementPlanCreateRequest */
        SupplementPlanCreateRequest: {
            /** Supplement Id */
            supplement_id: number;
            /** Dose */
            dose: number | string;
            time_of_day: components["schemas"]["TimeOfDay"];
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to?: string | null;
        };
        /** SupplementPlanResponse */
        SupplementPlanResponse: {
            /** Id */
            id: number;
            /** Supplement Id */
            supplement_id: number;
            /** Dose */
            dose: string;
            time_of_day: components["schemas"]["TimeOfDay"];
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to: string | null;
        };
        /**
         * SupplementPlanUpdateRequest
         * @description `PATCH /api/supplement-plans/{id}` 的請求 —— 見計畫陷阱 3。
         *
         *     這個端點**不修改**目標那一列的數值：它關閉舊期間、開一個新期間。
         *     三個欄位都可以省略（省略的欄位沿用舊列的值，`effective_date` 省略時
         *     預設「使用者時區的今天」），但比照 `UpdateMeRequest`（計畫 3 Task 3）
         *     的哨兵陷阱：**可以不帶，不接受明確的 null**——`X | None = None`
         *     這個型別本身無法區分「沒帶」跟「明確送 null」，兩者都要靠
         *     `model_fields_set` 與下面的驗證器分開處理，否則 null 會一路流到
         *     `setattr` 撞上資料庫的 NOT NULL，變成 500（計畫 3 Task 3 的教訓）。
         */
        SupplementPlanUpdateRequest: {
            /** Dose */
            dose?: number | string | null;
            time_of_day?: components["schemas"]["TimeOfDay"] | null;
            /** Effective Date */
            effective_date?: string | null;
        };
        /** SupplementResponse */
        SupplementResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Brand */
            brand: string | null;
            /** Is Global */
            is_global: boolean;
            /** Serving Unit */
            serving_unit: string;
            /** Serving Size */
            serving_size: string;
            /** Kcal */
            kcal: string;
            /** Protein G */
            protein_g: string;
            /** Fat G */
            fat_g: string;
            /** Carb G */
            carb_g: string;
        };
        /**
         * SupplementScope
         * @enum {string}
         */
        SupplementScope: "all" | "global" | "mine";
        /**
         * TargetCreateRequest
         * @description `POST /api/targets` 的請求（規格第 6.5 節 + 陷阱 3）。
         *
         *     四個營養素皆可省略（None）——允許使用者只設熱量目標、不設三大營養素。
         *     這裡用 Pydantic 的 `ge=0` 當第一道防線，資料庫的
         *     `CHECK (x IS NULL OR x >= 0)` 是第二道（且已實測：CHECK 對 NULL 一律放行，
         *     真正擋掉 NULL 的是欄位型別本身允許 NULL——這裡兩層防線擋的是「負值」，
         *     不是「NULL」，兩件事不要混為一談）。
         */
        TargetCreateRequest: {
            /** Kcal */
            kcal?: number | string | null;
            /** Protein G */
            protein_g?: number | string | null;
            /** Fat G */
            fat_g?: number | string | null;
            /** Carb G */
            carb_g?: number | string | null;
            /** Label */
            label?: string | null;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to?: string | null;
        };
        /** TargetResponse */
        TargetResponse: {
            /** Id */
            id: number;
            /** Kcal */
            kcal: string | null;
            /** Protein G */
            protein_g: string | null;
            /** Fat G */
            fat_g: string | null;
            /** Carb G */
            carb_g: string | null;
            /** Label */
            label: string | null;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to: string | null;
        };
        /**
         * TargetUpdateRequest
         * @description `PATCH /api/targets/{id}` 的請求 —— 決定 1：跟計畫 4a 的
         *     `supplement_plans` 同構，這不是原地修改，是「關閉舊期間、開新期間」。
         *
         *     但這個端點的 NULL 合法性矩陣跟 `SupplementPlanUpdateRequest` 不同：
         *     那邊的 `dose` / `time_of_day` 都是 NOT NULL，顯式 null 一律拒絕。這裡
         *     四個營養素跟 `label` 在資料庫都允許 NULL（陷阱 3：規格第 6.5 節），
         *     所以「顯式送 null」是合法輸入，語意是「清除這個欄位」——
         *     跟 `MealUpdateRequest` 的 `note` 是同一種取捨，只是這裡有五個欄位而不是一個。
         *
         *     `effective_from` 對應資料庫的 NOT NULL 欄位：可以省略（省略時預設「使用者
         *     時區的今天」，用 `today_in_timezone`，同 `supplement_plans` 的
         *     `effective_date`），但不接受顯式 `null`——那會一路流到 `setattr` 撞上
         *     NOT NULL（計畫 3 Task 3 的哨兵教訓，`_reject_explicit_null_on_non_nullable`
         *     這個名字跟 `MealUpdateRequest` 的驗證器同一個精神）。
         *
         *     `effective_to` 對應資料庫可為 NULL 的欄位：省略與顯式 `null` 都合法、
         *     效果也相同——都代表新開的這個期間是開放式的、沒有結束日。
         */
        TargetUpdateRequest: {
            /** Kcal */
            kcal?: number | string | null;
            /** Protein G */
            protein_g?: number | string | null;
            /** Fat G */
            fat_g?: number | string | null;
            /** Carb G */
            carb_g?: number | string | null;
            /** Label */
            label?: string | null;
            /** Effective From */
            effective_from?: string | null;
            /** Effective To */
            effective_to?: string | null;
        };
        /**
         * TimeOfDay
         * @enum {string}
         */
        TimeOfDay: "morning" | "noon" | "evening" | "bedtime" | "preworkout" | "postworkout";
        /**
         * TodaySupplementItem
         * @description `GET /api/supplements/today` 的一個項目 —— 陷阱 2：把「計畫」與
         *     「實際」對起來。`plan_id` 為 None 代表這是一筆臨時記錄（沒有對應的
         *     固定計畫），這種項目一定是 `done=True`（記錄本身就代表已經吃了）；
         *     `plan_id` 有值的項目才會有 `done=False` 的可能（計畫存在但今天還沒打卡）。
         */
        TodaySupplementItem: {
            /** Plan Id */
            plan_id: number | null;
            /** Supplement Id */
            supplement_id: number;
            /** Supplement Name */
            supplement_name: string;
            /** Dose */
            dose: string;
            time_of_day: components["schemas"]["TimeOfDay"] | null;
            /** Done */
            done: boolean;
            /** Intake Id */
            intake_id: number | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UpdateMeRequest
         * @description `PATCH /api/me` 的請求 —— 超出規格第 7.1 節的新增（見計畫 3 Task 3）。
         *
         *     範圍嚴格限制在 `display_name` 與 `timezone`：沒有 email、密碼、角色、
         *     刪除帳號，也沒有 `relationship()`。
         *
         *     兩個欄位都是 `X | None = None`，其中 `None` 是「這次請求沒帶這個欄位」的哨兵。
         *     路由層用 `model_dump(exclude_unset=True)` 決定要更新哪些欄位 ——
         *     不能用 `exclude_none`，兩者只在「client 明確送 null」時行為不同
         *     （`exclude_unset` 會保留、視為要求設成 null；`exclude_none` 會悄悄丟掉）。
         *
         *     **但這個哨兵寫法本身開了一個洞，實測踩到過：** Pydantic 在型別層
         *     分不出「沒帶」和「明確送 null」—— `X | None` 對兩者一律放行。
         *     而 `exclude_unset` 正確地保留了明確的 null，於是 `None` 一路流到
         *     `setattr`，撞上資料庫的 NOT NULL，變成已認證使用者就能觸發的 500
         *     （`asyncpg.NotNullViolationError`）。
         *
         *     修法不是退回 `exclude_none`（那會把明確的 null 悄悄吞掉，讓
         *     `{"timezone": null}` 靜默地變成 no-op），而是在這裡明講：
         *     **這兩個欄位可以不帶，但不接受 null。** 哨兵留給型別，語意由驗證器把關。
         */
        UpdateMeRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["UserRole"];
            /** Timezone */
            timezone: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "user" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_all_api_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update_me_api_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_foods_api_foods_get: {
        parameters: {
            query?: {
                q?: string | null;
                scope?: components["schemas"]["FoodScope"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_food_api_foods_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_frequent_foods_api_foods_frequent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recent_foods_api_foods_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_food_api_foods__food_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_revisions_api_foods__food_id__revisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_revision_api_foods__food_id__revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_portions_api_foods__food_id__portions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_portion_api_foods__food_id__portions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_revisions_api_admin_food_revisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingRevisionResponse"][];
                };
            };
        };
    };
    approve_revision_api_admin_food_revisions__revision_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_revision_api_admin_food_revisions__revision_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meals_api_meals_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_meal_api_meals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_meal_api_meals__meal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meal_api_meals__meal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meal_api_meals__meal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_meal_item_api_meals__meal_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealItemCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meal_item_api_meals__meal_id__items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_meal_photo_api_meals__meal_id__photo_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_meal_photo_api_meals__meal_id__photo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_meal_photo_api_meals__meal_id__photo_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meal_photo_api_meals__meal_id__photo_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_supplements_api_supplements_get: {
        parameters: {
            query?: {
                q?: string | null;
                scope?: components["schemas"]["SupplementScope"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplementResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_supplement_api_supplements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplementCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_today_api_supplements_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodaySupplementItem"][];
                };
            };
        };
    };
    list_plans_api_supplement_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplementPlanResponse"][];
                };
            };
        };
    };
    create_plan_api_supplement_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplementPlanCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplementPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_plan_api_supplement_plans__plan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plan_api_supplement_plans__plan_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplementPlanUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplementPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_intake_api_supplement_intakes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplementIntakeCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplementIntakeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_intake_api_supplement_intakes__intake_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intake_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_or_get_target_api_targets_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetResponse"][] | components["schemas"]["TargetResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_target_api_targets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_target_api_targets__target_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_stats_api_stats_daily_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_range_stats_api_stats_range_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RangeStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
